"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['MumboJumbo.py']
DATA_FILES = ['Image_Library', 'Info', 'Input', 'Output', 'Inverter_of_Truth.py', 'README.txt']
OPTIONS = {'iconfile':'Mumbo_Icon.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

#python3 setup.py py2app -A
